salsify/ember-css-modules

README.md

Added instructions to usage with addons for moving the dependency to the correct place. Added because this is a non-obvious step for new Ember developers.

Add addon usage gotcha

---

CHANGELOG.md
index.js
lib/htmlbars-plugin.js
lib/htmlbars-plugin/index.js
lib/htmlbars-plugin/utils.js
package.json
tests-node/htmlbars-plugin-test.js

Work in progress, but just opening it for exposure while I iterate on it.  I still need to implement support for `MustacheStatements` and `BlockStatements`.
Currently supported on `ElementNodes`:
```hbs
<button local-class="btn">Submit</button>
<button class="foo" local-class="btn">Submit</button>
<button class={{foo}} local-class="btn">Submit</button>
<button class="{{foo}}" local-class="btn">Submit</button>
{{#x-input class="btn" local-class="field input"}}...{{/x-input}}
{{x-input class="btn" local-class="field inout"}}
```
Gets preprocessed to:
```hbs
<button class="{{styles.btn}}">Submit</button>
<button class="foo {{styles.btn}}">Submit</button>
<button class="{{foo}} {{styles.btn}}">Submit</button>
<button class="{{foo}} {{styles.btn}}">Submit</button>
{{#x-foo class=(concat 'btn' …
```

Htmlbar plugin preprocessor for local-class attribute

---

addon/helpers/local-class.js
tests/unit/helpers/local-class-test.js

If we do something like 
```
local-class=(if foo 'active')
```
and foo is false, ember-css-modules will attempt to split on `undefined`. This PR fixes this issue by defaulting to an empty string.

Handle undefined local-class

---

package.json

Same logic as for why there is scheduling to run before ember-cli-sass & ember-cli-less.

Run before ember-cli-postcss

---

docs/POSTCSS.md
ember-cli-build.js
lib/output-styles-preprocessor.js
package.json
tests/dummy/app/components/testing/component-using-postprocess-plugin/styles.css
tests/dummy/app/components/testing/component-using-postprocess-plugin/template.hbs
tests/integration/component-using-postprocess-plugin-test.js
yarn.lock

Adds a new option to provide a set of PostCSS plugins to run after concatenation has taken place. This is useful for plugins like `postcss-sprites`, which should be run later in the CSS pipeline.
Closes salsify/broccoli-css-modules#3

Add postprocess plugin set

---

addon/mixins/component-mixin.js

Hi,
I was trying to use this addon within an existing project with `liquid-fire`. I stumble upon this error:
```
Assertion Failed: You cannot use `classNameBindings` on a tag-less component: <peakapp@component:liquid-outlet::ember235>
```
The problem is, that [`liquid-fire` use `tagName: ''` on its `outlet`](https://github.com/ember-animation/liquid-fire/blob/56156c599a4fed6c6db8572f85092ed07f91f2c8/addon/components/liquid-outlet.js#L12) and this addon doesn’t seem to like it :) The following solution fixed the issue in my app and I haven’t seen any downside. If you feel this is not the correct fix, feel free to guide me in the correct direction.
Keep up the good work!
✌️

Prevent classNameBindings on tag-less component

---

lib/plugin/registry.js

Corber creates a tree in which it has a live-reload pkg that looks like this
```
{ treeFor: [Function: treeFor],
pkg: { 'ember-addon': {} },
root: 'corber-livereload',
name: 'corber-livereload',
addons: [],
```
This breaks that line in the registry as it expects every package to have keywords

Fixes to work with corber / any package without keywords

---

package.json

This makes `{{fa-icon iconName local-class="some-icon"}}` compatible with ember-font-awesome@v4, which now uses an HTMLBars AST transform to replace all invocations of `{{fa-icon}}` with a plain HTML `<i>` tag.
Ironically ember-css-modules has to be included *after* ember-font-awesome in order for its transforms to run before ember-font-awesome.
I have absolutely no idea why though. ¯\_(ツ)_/¯

fix(package): run after ember-font-awesome

---

addon/decorators.js

As correctly pointed out in https://github.com/salsify/ember-css-modules/pull/101#issuecomment-423204133, the implementation of these decorators is based on the original work of [ember-osf-web](https://github.com/CenterForOpenScience/ember-osf-web/blob/4675920c4d53e60c62eed7a87ea84e0f4c5ab018/app/decorators/css-modules.ts), which is released under the Apache License 2.0, which allows reuse in derivative works (such as this), but requires attribution. In order to comply with this license, this PR adds the attribution as comment in the source code.
/cc @binoculars

Attribute ember-osf-web as the basis for the decorators implementation

---

addon/decorators.js
package.json
tests/integration/decorators-test.js
yarn.lock

@jamescdavis has found, that you cannot decorate getters, because we set the `writable` flag here:
https://github.com/salsify/ember-css-modules/blob/d4952bee14ca090e33542bc143a7b7a64b05662a/addon/decorators.js#L84-L87
This PR attempts to fix that.
As a first step I have added failing tests for decorating plain ES5 getters and computed properties.

fix(decorators): decorating getters

---

package.json
yarn.lock

We ran into a bug due to the previous `broccoli-postcss`'s [strict reliance on a specific `broccoli-persistent-filter` version](https://github.com/jeffjewiss/broccoli-postcss/blob/v3.5.3/package.json#L36)
The `broccoli-postcss` upgrade [brings the PostCSS version up to 7](https://github.com/jeffjewiss/broccoli-postcss/blob/master/CHANGELOG.md#400). This _might_ mean that landing this PR would require a breaking change here, too.
Both the major-version bump in PostCSS and the broccoli plugin drop Node 4 and 9 support, but this addon never tried to be compatible with either of those anyway, based on the declared `engine`. PostCSS does have some other breaking changes around browser support, however, but it's mostly for dead browsers. You can find the relevant changelog …

chore(deps): upgrade to `broccoli-postcss` 4

---

.travis.yml
addon/decorators.js
config/ember-try.js
package.json
tests-node/acceptance/plugins-test.js
tests/integration/decorators-test.js
yarn.lock

This updates our dependency on `@ember-decorators/utils` to ^3.1, which handles abstracting away the differences between the stage 1 and stage 2 versions of the decorators proposal.
/cc @buschtoens

Support stage-2 decorators

---

package.json
yarn.lock

Technically we already do; this just widens our version specifier for `@ember-decorators/utils`.

Support ember-decorators packages @ 5.x

---

addon/mixins/component-mixin.js

https://github.com/emberjs/ember.js/pull/18096
This PR changed how templates are used under the hood. Template modules now export a factory function that expects to be called with the `owner`.

fix: support template factory

---

README.md

Support for Octane-style colocation exists, but currently only in the beta version.
This PR adds a note to the README to help people understand that, until the obstacles to supporting it in the stable version are addressed.
Related: #151.

Document beta version requirement for colocation support

---

docs/VIRTUAL_MODULES.md
packages/ember-css-modules/index.js
packages/ember-css-modules/lib/resolve-path.js

This will fix #166 (or at least the original error reported there). Now, a typo in an import path will no longer give the cryptic error message:
```
Unable to resolve styles from addon ; is it installed?
```
Instead, devs will see:
```
Unable to resolve styles module 'oops/a/typo' imported from
'<importing file>.css'. No virtual module with that name was
defined and no corresponding addon was found.
```
It also updates the guidance in the virtual modules documentation due to the config calculation timing changes that were necessary to support component/template colocation.

Restore 1.2.x timing for config calculation

---

packages/ember-css-modules/lib/resolve-path.js

Exactly how modules are presented within a broccoli tree varies pretty widely over different ember-cli versions, and while adding Embroider to the mix will hopefully eventually simplify that, in the short term it just means one more set of behaviors we have to juggle. ECM 1.3.0 apparently broke resolution of absolute intra-package imports for some range of ember-cli versions newer than the oldest we support, but older than 3.13, as @jamescdavis discovered.

Ensure local imports work with CLI 3.12

---

CHANGELOG.md
packages/ember-css-modules/package.json

This PR ensures that `ember-css-modules` is initialized before `ember-cli-htmlbars`.
This almost always was coincidentally the case already, but ordering constraints from other addons _could_ cause ECM to init later, causing `local-class` in colocated templates not to be processed.
This _should_ fix chancancode/ember-concurrency-async#4.

Ensure ember-css-modules inits before ember-cli-htmlbars

---

README.md
packages/ember-css-modules/index.js

This PR updates behavior so that addons using ECM that don't specify their own `generateScopedName` will use the host app's config if any is specified, rather than immediately falling back to the default implementation.
This makes it possible for apps to configure scoped name generation universally without having to figure out a way to plumb that information through to individual subpackages.

Addons default to the root app's `generateScopedName` config

---

CHANGELOG.md
packages/ember-css-modules/lib/make-postcss-plugin.js
packages/ember-css-modules/lib/modules-preprocessor.js
packages/ember-css-modules/lib/output-styles-preprocessor.js
packages/ember-css-modules/lib/postcss-module-order-directive.js
packages/ember-css-modules/package.json
packages/ember-css-modules/tests/dummy/app/styles/testing/ordering/x.css
packages/ember-css-modules/tests/dummy/app/styles/testing/ordering/y.css
packages/ember-css-modules/tests/dummy/app/styles/testing/ordering/z.css
test-packages/old-app/README.md
test-packages/old-app/package.json
test-packages/old-app/yarn.lock
yarn.lock

This PR widens the range of dependencies we'll accept, effectively moving our default pipeline to PostCSS 8. All of the previous versions of these packages are still in-range for ECM itself, and `test-packages/old-app` demonstrates this by continuing to use those and compile successfully with Node 6. (Or at least it's all green locally; we'll see if CI agrees.)
Closes #218.

Support PostCSS 8

---

CHANGELOG.md
packages/ember-css-modules/addon/mixins/component-mixin.js
yarn.lock

This PR deprecates the `localClassNames` and `localClassNameBindings` properties on `Ember.Component` subclasses, as well as the `@localClassName` and `@localClassNames` decorators that can be used as sugar for the same.
These APIs rely on reopening the `Ember.Component` base class, which is deprecated as of [emberjs/rfcs#671](https://github.com/emberjs/rfcs/pull/671), and they also belong to the pre-Octane programming model for Ember applications, since Glimmer components have no implicit root element for those APIs to even operate on. Accordingly, we'd like to drop them for `ember-css-modules@2`.
The changelog contains further details and several different recommendations for ways of migrating off of these APIs.

Deprecate `localClassNames` and friends

---

packages/ember-css-modules/lib/resolve-path.js
yarn.lock

Right now, if a component file includes the name of its containing addon, the old logic would find that `appOrAddonDirIndex` would not be `-1`, when in reality it should be.
EX: addon name is `special-button`
```css
/* special-button/addon/components/special-button.css */
.special-button {
composes: special from 'special-button/components/base-specialness';
}
```
With parameters like this (this is how it looks in our embroider build):
```js
importPath        === 'special-button/components/base-specialness';
fromFile          === '/tmp/broccoli-4392qIAomevRxZbJ/out-03-module_source_funnel/components/special-button.css';
options.root      === '/tmp/broccoli-4392qIAomevRxZbJ/out-03-module_source_funnel/';
options.ownerName === 'special-button';
```
In the old logic, we would get something …

fixes resolve-path logic for finding local paths that include an addon's name

---

packages/ember-css-modules/index.js

opt-in to address #237 until a breaking release is made.
This would allow you to specify:
```js
let app = new EmberAddon(defaults, {
cssModules: {
patchClassicComponent: false
}
});
```
Avoid the deprecation `Reopening the Ember.Component super class itself is deprecated` if you do not use classic components (or the bindings on classic components, at least).
Thanks to @Turbo87 and @mydea for idea.
Closes #237.

Allow to opt out of classic component patching
